### ISSUE TITLE
Undocumented plow event codes

### ISSUE THREAD

**Issue by hannta** [City-of-Helsinki/aura#1]
Right now API returns plow events like "ln", "hn", "ps" and "pe". Please add these to documentation with descriptions.

**Comment by juyrjola** [comment]
Thanks for your report, the  [API documentation](https://github.com/City-of-Helsinki/aura/wiki/API) has now been updated.

**Comment by ilarischeinin** [comment]
Looks like new codes have been introduced again, and the documentation is not up to date. The new ones I see are "hj" (harjaus?) and "pn".

**Comment by juyrjola** [comment]
@ilarischeinin: I've updated the API documentation to include:

hj = Brushing (harjaus)
pn = Coating (pinnoitus, liittyy kesähoitoreitteihin)
